source $HOME/.zsh/aliases/index
source $HOME/.zsh/prompt
source $HOME/.zsh/version-managers

# Use UTC.
export TZ=utc

# Load sensitive data.
source $HOME/.zsh/env

# Load shortcuts.
source $HOME/.zsh/shortcuts

# Use Vim mode for command line.
bindkey -v

# Use Vim as default editor.
export EDITOR='vim'

# Use colors.
autoload -U colors
colors

# Enable colored output from commands.
export CLICOLOR=1

# Store lots of history.
export HISTSIZE=500

# Use Command-R to search through history.
bindkey '^R' history-incremental-search-backward

# Don't show partial lines.
unsetopt PROMPT_SP
